version: 2

updates:
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
      day: friday

  - package-ecosystem: docker
    directories:
      - '/folia/'
      - '/paper/'
      - '/velocity/'
    ignore:
      - dependency-name: eclipse-temurin
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
      day: friday

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
