name: Synchronize Paper

on:
  schedule:
    - cron: '0 0 * * FRI'
  workflow_dispatch:
    inputs:
      force:
        default: false
        description: Force build all Paper images
        type: boolean

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  synchronize:
    secrets: inherit
    uses: ./.github/workflows/synchronize.yml
    permissions:
      contents: read
      packages: write

    with:
      force: ${{ inputs.force || false }}
      project: paper
